process.env.DB_HOST = 'localhost';
process.env.DB_PORT = '5433';       // FIX: puerto expuesto al host por el otro compose
process.env.DB_USER = 'u_ride_user'; // FIX: usuario real del otro compose
process.env.DB_PASSWORD = 'secure_password_123';
process.env.DB_NAME = 'u_ride_dev';  // FIX: nombre real del otro compose
process.env.NODE_ENV = 'test';
process.env.JWT_SECRET = 'test_secret';
process.env.JWT_REFRESH_SECRET = 'test_refresh_secret';
process.env.EMAIL_DEV_MODE = 'true';